version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: db
    ports:
      - 15306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
  localstack:
    image: localstack/localstack
    container_name: lst
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - "./data/localstack:/var/lib/localstack"
